// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-daily-stats.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.50.3";
import { z } from "npm:zod@^3.25.76";
function admin() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_daily_stats_default = defineTool({
  name: "get_daily_stats",
  title: "Get daily attendance stats",
  description: "Aggregate attendance counts for a given date (YYYY-MM-DD) across the in-person queue and WhatsApp services.",
  inputSchema: {
    date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Target date in YYYY-MM-DD format (America/Sao_Paulo).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }) => {
    const start = `${date}T00:00:00-03:00`;
    const end = `${date}T23:59:59-03:00`;
    const sb = admin();
    const [queueTotal, queueCompleted, whats] = await Promise.all([
      sb.from("queue_customers").select("*", { count: "exact", head: true }).gte("created_at", start).lte("created_at", end),
      sb.from("queue_customers").select("*", { count: "exact", head: true }).eq("status", "completed").gte("completed_at", start).lte("completed_at", end),
      sb.from("whatsapp_services").select("*", { count: "exact", head: true }).gte("created_at", start).lte("created_at", end)
    ]);
    const payload = {
      date,
      queue_total: queueTotal.count ?? 0,
      queue_completed: queueCompleted.count ?? 0,
      whatsapp_services: whats.count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-service-locations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.50.3";
var list_service_locations_default = defineTool2({
  name: "list_service_locations",
  title: "List service locations",
  description: "List active service locations (secretarias/unidades) available in the attendance system.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const sb = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await sb.from("service_locations").select("id,name,active").eq("active", true).order("name");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { locations: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "getulio-atende-mcp",
  title: "Get\xFAlio Atende Digital MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the Presidente Get\xFAlio municipal attendance system. Use `get_daily_stats` to fetch aggregate attendance counts for a date, and `list_service_locations` to enumerate active service locations.",
  tools: [get_daily_stats_default, list_service_locations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
